name: 'self_serve_analytics'
version: '1.0.0'
config-version: 2

profile: 'self_serve_analytics'

model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]

models:
  self_serve_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: view